// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: authen.api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AUTHEN_TYPE_ID int32

const (
	AUTHEN_TYPE_ID_AUTHEN_NONE      AUTHEN_TYPE_ID = 0
	AUTHEN_TYPE_ID_REQUEST_LOGIN    AUTHEN_TYPE_ID = 1
	AUTHEN_TYPE_ID_REQUEST_REGISTER AUTHEN_TYPE_ID = 2
	AUTHEN_TYPE_ID_REQUEST_AUTHEN   AUTHEN_TYPE_ID = 3
)

// Enum value maps for AUTHEN_TYPE_ID.
var (
	AUTHEN_TYPE_ID_name = map[int32]string{
		0: "AUTHEN_NONE",
		1: "REQUEST_LOGIN",
		2: "REQUEST_REGISTER",
		3: "REQUEST_AUTHEN",
	}
	AUTHEN_TYPE_ID_value = map[string]int32{
		"AUTHEN_NONE":      0,
		"REQUEST_LOGIN":    1,
		"REQUEST_REGISTER": 2,
		"REQUEST_AUTHEN":   3,
	}
)

func (x AUTHEN_TYPE_ID) Enum() *AUTHEN_TYPE_ID {
	p := new(AUTHEN_TYPE_ID)
	*p = x
	return p
}

func (x AUTHEN_TYPE_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AUTHEN_TYPE_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_authen_api_proto_enumTypes[0].Descriptor()
}

func (AUTHEN_TYPE_ID) Type() protoreflect.EnumType {
	return &file_authen_api_proto_enumTypes[0]
}

func (x AUTHEN_TYPE_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AUTHEN_TYPE_ID.Descriptor instead.
func (AUTHEN_TYPE_ID) EnumDescriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{0}
}

type AUTHEN_GROUP int32

const (
	AUTHEN_GROUP_AUTHEN_GROUP_UN_USE AUTHEN_GROUP = 0
	AUTHEN_GROUP_AUTHEN_GROUP_ID     AUTHEN_GROUP = 2
)

// Enum value maps for AUTHEN_GROUP.
var (
	AUTHEN_GROUP_name = map[int32]string{
		0: "AUTHEN_GROUP_UN_USE",
		2: "AUTHEN_GROUP_ID",
	}
	AUTHEN_GROUP_value = map[string]int32{
		"AUTHEN_GROUP_UN_USE": 0,
		"AUTHEN_GROUP_ID":     2,
	}
)

func (x AUTHEN_GROUP) Enum() *AUTHEN_GROUP {
	p := new(AUTHEN_GROUP)
	*p = x
	return p
}

func (x AUTHEN_GROUP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AUTHEN_GROUP) Descriptor() protoreflect.EnumDescriptor {
	return file_authen_api_proto_enumTypes[1].Descriptor()
}

func (AUTHEN_GROUP) Type() protoreflect.EnumType {
	return &file_authen_api_proto_enumTypes[1]
}

func (x AUTHEN_GROUP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AUTHEN_GROUP.Descriptor instead.
func (AUTHEN_GROUP) EnumDescriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{1}
}

type Login_ERROR int32

const (
	Login_NO_ERROR                        Login_ERROR = 0
	Login_USER_NAME_INVALID               Login_ERROR = 1
	Login_PASSWORD_INVALID                Login_ERROR = 2
	Login_USER_NOT_FOUND                  Login_ERROR = 3
	Login_USER_NOT_ACTIVE                 Login_ERROR = 4
	Login_USER_NAME_OR_PASSWORD_NOT_MATCH Login_ERROR = 5
)

// Enum value maps for Login_ERROR.
var (
	Login_ERROR_name = map[int32]string{
		0: "NO_ERROR",
		1: "USER_NAME_INVALID",
		2: "PASSWORD_INVALID",
		3: "USER_NOT_FOUND",
		4: "USER_NOT_ACTIVE",
		5: "USER_NAME_OR_PASSWORD_NOT_MATCH",
	}
	Login_ERROR_value = map[string]int32{
		"NO_ERROR":                        0,
		"USER_NAME_INVALID":               1,
		"PASSWORD_INVALID":                2,
		"USER_NOT_FOUND":                  3,
		"USER_NOT_ACTIVE":                 4,
		"USER_NAME_OR_PASSWORD_NOT_MATCH": 5,
	}
)

func (x Login_ERROR) Enum() *Login_ERROR {
	p := new(Login_ERROR)
	*p = x
	return p
}

func (x Login_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Login_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_authen_api_proto_enumTypes[2].Descriptor()
}

func (Login_ERROR) Type() protoreflect.EnumType {
	return &file_authen_api_proto_enumTypes[2]
}

func (x Login_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Login_ERROR.Descriptor instead.
func (Login_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{0, 0}
}

type Register_ERROR int32

const (
	Register_NO_ERROR          Register_ERROR = 0
	Register_USER_NAME_INVALID Register_ERROR = 1
	Register_PASSWORD_INVALID  Register_ERROR = 2
	Register_EMAIL_INVALID     Register_ERROR = 3
	Register_TEL_INVALID       Register_ERROR = 4
	Register_USER_EXISTED      Register_ERROR = 5
	Register_TEL_EXISTED       Register_ERROR = 6
	Register_EMAIL_EXISTED     Register_ERROR = 7
)

// Enum value maps for Register_ERROR.
var (
	Register_ERROR_name = map[int32]string{
		0: "NO_ERROR",
		1: "USER_NAME_INVALID",
		2: "PASSWORD_INVALID",
		3: "EMAIL_INVALID",
		4: "TEL_INVALID",
		5: "USER_EXISTED",
		6: "TEL_EXISTED",
		7: "EMAIL_EXISTED",
	}
	Register_ERROR_value = map[string]int32{
		"NO_ERROR":          0,
		"USER_NAME_INVALID": 1,
		"PASSWORD_INVALID":  2,
		"EMAIL_INVALID":     3,
		"TEL_INVALID":       4,
		"USER_EXISTED":      5,
		"TEL_EXISTED":       6,
		"EMAIL_EXISTED":     7,
	}
)

func (x Register_ERROR) Enum() *Register_ERROR {
	p := new(Register_ERROR)
	*p = x
	return p
}

func (x Register_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Register_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_authen_api_proto_enumTypes[3].Descriptor()
}

func (Register_ERROR) Type() protoreflect.EnumType {
	return &file_authen_api_proto_enumTypes[3]
}

func (x Register_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Register_ERROR.Descriptor instead.
func (Register_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{1, 0}
}

type AuthConnection_ERROR int32

const (
	AuthConnection_NO_ERROR           AuthConnection_ERROR = 0
	AuthConnection_SID_INVALID        AuthConnection_ERROR = 1
	AuthConnection_UID_INVALID        AuthConnection_ERROR = 2
	AuthConnection_ACCOUNT_NOT_ACTIVE AuthConnection_ERROR = 3
	AuthConnection_ACCOUNT_BANTED     AuthConnection_ERROR = 4
	AuthConnection_SESSION_EXPIRE     AuthConnection_ERROR = 5
	AuthConnection_ACCOUNT_NOT_FOUND  AuthConnection_ERROR = 6
)

// Enum value maps for AuthConnection_ERROR.
var (
	AuthConnection_ERROR_name = map[int32]string{
		0: "NO_ERROR",
		1: "SID_INVALID",
		2: "UID_INVALID",
		3: "ACCOUNT_NOT_ACTIVE",
		4: "ACCOUNT_BANTED",
		5: "SESSION_EXPIRE",
		6: "ACCOUNT_NOT_FOUND",
	}
	AuthConnection_ERROR_value = map[string]int32{
		"NO_ERROR":           0,
		"SID_INVALID":        1,
		"UID_INVALID":        2,
		"ACCOUNT_NOT_ACTIVE": 3,
		"ACCOUNT_BANTED":     4,
		"SESSION_EXPIRE":     5,
		"ACCOUNT_NOT_FOUND":  6,
	}
)

func (x AuthConnection_ERROR) Enum() *AuthConnection_ERROR {
	p := new(AuthConnection_ERROR)
	*p = x
	return p
}

func (x AuthConnection_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthConnection_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_authen_api_proto_enumTypes[4].Descriptor()
}

func (AuthConnection_ERROR) Type() protoreflect.EnumType {
	return &file_authen_api_proto_enumTypes[4]
}

func (x AuthConnection_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthConnection_ERROR.Descriptor instead.
func (AuthConnection_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{2, 0}
}

// / JSON REQUEST {"type":1, "group":"AUTHEN", "request":{"@type":"type.googleapis.com/Login.Request", "userName":"admin", "password":"admin"}}
// / JSON REPLY {"reply":{"@type":"type.googleapis.com/Login.Reply", "session":{"userId":"1", "sessionId":"c7ba3cc8-a1fe-11ed-9f49-0242ac130002", "expire":"1677827116", "lastActive":"1675235116", "role":2}}}
type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{0}
}

// / JSON REQUEST {"type":2,"group":"AUTHEN","request":{"@type":"type.googleapis.com/Register.Request","userName":"admin","password":"admin","email":"dungnt@vivas.vn","tel":"034535285","deviceToken":"12345","platform":"ANDROID"}}
// / JSON REPLY {"reply":{"@type":"type.googleapis.com/Register.Reply", "session":{"userId":"1", "sessionId":"c7ba3cc8-a1fe-11ed-9f49-0242ac130002", "expire":"1677827116", "lastActive":"1675235116", "role":2}}}
type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{1}
}

// xác thực token của http request
// REPLY  ==> {"reply":{"@type":"type.googleapis.com/AuthConnection.Reply", "session":{"userId":"2", "sessionId":"1d916c27-a1e0-11ed-95f6-0242ac130002", "expire":"1677813945", "lastActive":"1675221945", "role":2}}}
type AuthConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthConnection) Reset() {
	*x = AuthConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConnection) ProtoMessage() {}

func (x *AuthConnection) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConnection.ProtoReflect.Descriptor instead.
func (*AuthConnection) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{2}
}

type Login_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName    string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceToken string `protobuf:"bytes,3,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Platform    uint32 `protobuf:"varint,4,opt,name=platform,proto3" json:"platform,omitempty"`
}

func (x *Login_Request) Reset() {
	*x = Login_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Request) ProtoMessage() {}

func (x *Login_Request) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Request.ProtoReflect.Descriptor instead.
func (*Login_Request) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Login_Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Login_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Login_Request) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *Login_Request) GetPlatform() uint32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

type Login_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *Login_Reply) Reset() {
	*x = Login_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Reply) ProtoMessage() {}

func (x *Login_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Reply.ProtoReflect.Descriptor instead.
func (*Login_Reply) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Login_Reply) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type Register_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName    string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Tel         string `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
	DeviceToken string `protobuf:"bytes,5,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Platform    uint32 `protobuf:"varint,6,opt,name=platform,proto3" json:"platform,omitempty"`
}

func (x *Register_Request) Reset() {
	*x = Register_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register_Request) ProtoMessage() {}

func (x *Register_Request) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register_Request.ProtoReflect.Descriptor instead.
func (*Register_Request) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Register_Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Register_Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Register_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Register_Request) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *Register_Request) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *Register_Request) GetPlatform() uint32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

type Register_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *Register_Reply) Reset() {
	*x = Register_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register_Reply) ProtoMessage() {}

func (x *Register_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register_Reply.ProtoReflect.Descriptor instead.
func (*Register_Reply) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Register_Reply) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type AuthConnection_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid string `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *AuthConnection_Request) Reset() {
	*x = AuthConnection_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthConnection_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConnection_Request) ProtoMessage() {}

func (x *AuthConnection_Request) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConnection_Request.ProtoReflect.Descriptor instead.
func (*AuthConnection_Request) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AuthConnection_Request) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *AuthConnection_Request) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type AuthConnection_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *AuthConnection_Reply) Reset() {
	*x = AuthConnection_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authen_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthConnection_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConnection_Reply) ProtoMessage() {}

func (x *AuthConnection_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_authen_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConnection_Reply.ProtoReflect.Descriptor instead.
func (*AuthConnection_Reply) Descriptor() ([]byte, []int) {
	return file_authen_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *AuthConnection_Reply) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_authen_api_proto protoreflect.FileDescriptor

var file_authen_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x02,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x80, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x1a, 0x2b, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x90, 0x01, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12,
	0x15, 0x0a, 0x11, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f,
	0x52, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x03,
	0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x54,
	0x49, 0x56, 0x45, 0x10, 0x04, 0x12, 0x23, 0x0a, 0x1f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x41,
	0x4d, 0x45, 0x5f, 0x4f, 0x52, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x05, 0x22, 0x81, 0x03, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a, 0xa8, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x1a, 0x2b, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x07, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x9c, 0x01, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x45, 0x4c, 0x5f, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x53, 0x45, 0x52,
	0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x45, 0x44, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x45,
	0x4c, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x45, 0x44, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x45,
	0x4d, 0x41, 0x49, 0x4c, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x45, 0x44, 0x10, 0x07, 0x22, 0xfd,
	0x01, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x2d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x1a, 0x2b, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x07, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8e, 0x01,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x49, 0x44, 0x5f, 0x49, 0x4e, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x49, 0x44, 0x5f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x03, 0x12,
	0x12, 0x0a, 0x0e, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x42, 0x41, 0x4e, 0x54, 0x45,
	0x44, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x45,
	0x58, 0x50, 0x49, 0x52, 0x45, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x43, 0x43, 0x4f, 0x55,
	0x4e, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x06, 0x2a, 0x5e,
	0x0a, 0x0e, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x44,
	0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4c, 0x4f, 0x47,
	0x49, 0x4e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f,
	0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x10, 0x03, 0x2a, 0x3c,
	0x0a, 0x0c, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x12, 0x17,
	0x0a, 0x13, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x55,
	0x4e, 0x5f, 0x55, 0x53, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x55, 0x54, 0x48, 0x45,
	0x4e, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x49, 0x44, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04,
	0x61, 0x70, 0x69, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authen_api_proto_rawDescOnce sync.Once
	file_authen_api_proto_rawDescData = file_authen_api_proto_rawDesc
)

func file_authen_api_proto_rawDescGZIP() []byte {
	file_authen_api_proto_rawDescOnce.Do(func() {
		file_authen_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_authen_api_proto_rawDescData)
	})
	return file_authen_api_proto_rawDescData
}

var file_authen_api_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_authen_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_authen_api_proto_goTypes = []interface{}{
	(AUTHEN_TYPE_ID)(0),            // 0: AUTHEN_TYPE_ID
	(AUTHEN_GROUP)(0),              // 1: AUTHEN_GROUP
	(Login_ERROR)(0),               // 2: Login.ERROR
	(Register_ERROR)(0),            // 3: Register.ERROR
	(AuthConnection_ERROR)(0),      // 4: AuthConnection.ERROR
	(*Login)(nil),                  // 5: Login
	(*Register)(nil),               // 6: Register
	(*AuthConnection)(nil),         // 7: AuthConnection
	(*Login_Request)(nil),          // 8: Login.Request
	(*Login_Reply)(nil),            // 9: Login.Reply
	(*Register_Request)(nil),       // 10: Register.Request
	(*Register_Reply)(nil),         // 11: Register.Reply
	(*AuthConnection_Request)(nil), // 12: AuthConnection.Request
	(*AuthConnection_Reply)(nil),   // 13: AuthConnection.Reply
	(*Session)(nil),                // 14: Session
}
var file_authen_api_proto_depIdxs = []int32{
	14, // 0: Login.Reply.session:type_name -> Session
	14, // 1: Register.Reply.session:type_name -> Session
	14, // 2: AuthConnection.Reply.session:type_name -> Session
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_authen_api_proto_init() }
func file_authen_api_proto_init() {
	if File_authen_api_proto != nil {
		return
	}
	file_api_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_authen_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthConnection_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authen_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthConnection_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authen_api_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authen_api_proto_goTypes,
		DependencyIndexes: file_authen_api_proto_depIdxs,
		EnumInfos:         file_authen_api_proto_enumTypes,
		MessageInfos:      file_authen_api_proto_msgTypes,
	}.Build()
	File_authen_api_proto = out.File
	file_authen_api_proto_rawDesc = nil
	file_authen_api_proto_goTypes = nil
	file_authen_api_proto_depIdxs = nil
}
