// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: connect.api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TYPE_ID int32

const (
	TYPE_ID__NONE             TYPE_ID = 0
	TYPE_ID_RECEIVE_HELLO     TYPE_ID = 1
	TYPE_ID_REQUEST_HELLO     TYPE_ID = 2
	TYPE_ID_REQUEST_KEEPALIVE TYPE_ID = 3
)

// Enum value maps for TYPE_ID.
var (
	TYPE_ID_name = map[int32]string{
		0: "_NONE",
		1: "RECEIVE_HELLO",
		2: "REQUEST_HELLO",
		3: "REQUEST_KEEPALIVE",
	}
	TYPE_ID_value = map[string]int32{
		"_NONE":             0,
		"RECEIVE_HELLO":     1,
		"REQUEST_HELLO":     2,
		"REQUEST_KEEPALIVE": 3,
	}
)

func (x TYPE_ID) Enum() *TYPE_ID {
	p := new(TYPE_ID)
	*p = x
	return p
}

func (x TYPE_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_connect_api_proto_enumTypes[0].Descriptor()
}

func (TYPE_ID) Type() protoreflect.EnumType {
	return &file_connect_api_proto_enumTypes[0]
}

func (x TYPE_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE_ID.Descriptor instead.
func (TYPE_ID) EnumDescriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{0}
}

type Hello_ERROR int32

const (
	Hello_NO_ERROR            Hello_ERROR = 0
	Hello_PKEY_INVALID        Hello_ERROR = 1
	Hello_ENCODE_TYPE_INVALID Hello_ERROR = 2
)

// Enum value maps for Hello_ERROR.
var (
	Hello_ERROR_name = map[int32]string{
		0: "NO_ERROR",
		1: "PKEY_INVALID",
		2: "ENCODE_TYPE_INVALID",
	}
	Hello_ERROR_value = map[string]int32{
		"NO_ERROR":            0,
		"PKEY_INVALID":        1,
		"ENCODE_TYPE_INVALID": 2,
	}
)

func (x Hello_ERROR) Enum() *Hello_ERROR {
	p := new(Hello_ERROR)
	*p = x
	return p
}

func (x Hello_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hello_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_connect_api_proto_enumTypes[1].Descriptor()
}

func (Hello_ERROR) Type() protoreflect.EnumType {
	return &file_connect_api_proto_enumTypes[1]
}

func (x Hello_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hello_ERROR.Descriptor instead.
func (Hello_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{1, 0}
}

type KeepAlive_ERROR int32

const (
	KeepAlive_NO_ERROR              KeepAlive_ERROR = 0
	KeepAlive_CONNECTION_ID_INVALID KeepAlive_ERROR = 1
)

// Enum value maps for KeepAlive_ERROR.
var (
	KeepAlive_ERROR_name = map[int32]string{
		0: "NO_ERROR",
		1: "CONNECTION_ID_INVALID",
	}
	KeepAlive_ERROR_value = map[string]int32{
		"NO_ERROR":              0,
		"CONNECTION_ID_INVALID": 1,
	}
)

func (x KeepAlive_ERROR) Enum() *KeepAlive_ERROR {
	p := new(KeepAlive_ERROR)
	*p = x
	return p
}

func (x KeepAlive_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeepAlive_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_connect_api_proto_enumTypes[2].Descriptor()
}

func (KeepAlive_ERROR) Type() protoreflect.EnumType {
	return &file_connect_api_proto_enumTypes[2]
}

func (x KeepAlive_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeepAlive_ERROR.Descriptor instead.
func (KeepAlive_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{2, 0}
}

type HelloReceive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime       uint64     `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ServerEncodeType EncodeType `protobuf:"varint,2,opt,name=server_encodeType,json=serverEncodeType,proto3,enum=EncodeType" json:"server_encodeType,omitempty"`
	PKey             []byte     `protobuf:"bytes,3,opt,name=pKey,proto3" json:"pKey,omitempty"`
}

func (x *HelloReceive) Reset() {
	*x = HelloReceive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReceive) ProtoMessage() {}

func (x *HelloReceive) ProtoReflect() protoreflect.Message {
	mi := &file_connect_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReceive.ProtoReflect.Descriptor instead.
func (*HelloReceive) Descriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReceive) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HelloReceive) GetServerEncodeType() EncodeType {
	if x != nil {
		return x.ServerEncodeType
	}
	return EncodeType_NONE
}

func (x *HelloReceive) GetPKey() []byte {
	if x != nil {
		return x.PKey
	}
	return nil
}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_connect_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{1}
}

type KeepAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_connect_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{2}
}

type Hello_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncodeType EncodeType `protobuf:"varint,1,opt,name=encodeType,proto3,enum=EncodeType" json:"encodeType,omitempty"` // loại mã hóa mà client sử dụng
	PKey       []byte     `protobuf:"bytes,2,opt,name=pKey,proto3" json:"pKey,omitempty"`                              // public key của client , có thể là rsa public key hoặc xor key
	Platform   Platform   `protobuf:"varint,3,opt,name=platform,proto3,enum=Platform" json:"platform,omitempty"`
}

func (x *Hello_Request) Reset() {
	*x = Hello_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello_Request) ProtoMessage() {}

func (x *Hello_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connect_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello_Request.ProtoReflect.Descriptor instead.
func (*Hello_Request) Descriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Hello_Request) GetEncodeType() EncodeType {
	if x != nil {
		return x.EncodeType
	}
	return EncodeType_NONE
}

func (x *Hello_Request) GetPKey() []byte {
	if x != nil {
		return x.PKey
	}
	return nil
}

func (x *Hello_Request) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_IOS
}

type Hello_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionId     []byte     `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ServerTime       uint64     `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ServerEncodeType EncodeType `protobuf:"varint,3,opt,name=server_encodeType,json=serverEncodeType,proto3,enum=EncodeType" json:"server_encodeType,omitempty"`
	PKey             []byte     `protobuf:"bytes,4,opt,name=pKey,proto3" json:"pKey,omitempty"`
}

func (x *Hello_Reply) Reset() {
	*x = Hello_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello_Reply) ProtoMessage() {}

func (x *Hello_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_connect_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello_Reply.ProtoReflect.Descriptor instead.
func (*Hello_Reply) Descriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Hello_Reply) GetConnectionId() []byte {
	if x != nil {
		return x.ConnectionId
	}
	return nil
}

func (x *Hello_Reply) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *Hello_Reply) GetServerEncodeType() EncodeType {
	if x != nil {
		return x.ServerEncodeType
	}
	return EncodeType_NONE
}

func (x *Hello_Reply) GetPKey() []byte {
	if x != nil {
		return x.PKey
	}
	return nil
}

type KeepAlive_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectionId []byte `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
}

func (x *KeepAlive_Request) Reset() {
	*x = KeepAlive_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAlive_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive_Request) ProtoMessage() {}

func (x *KeepAlive_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connect_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive_Request.ProtoReflect.Descriptor instead.
func (*KeepAlive_Request) Descriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *KeepAlive_Request) GetConnectionId() []byte {
	if x != nil {
		return x.ConnectionId
	}
	return nil
}

type KeepAlive_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeepAlive_Reply) Reset() {
	*x = KeepAlive_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connect_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAlive_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive_Reply) ProtoMessage() {}

func (x *KeepAlive_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_connect_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive_Reply.ProtoReflect.Descriptor instead.
func (*KeepAlive_Reply) Descriptor() ([]byte, []int) {
	return file_connect_api_proto_rawDescGZIP(), []int{2, 1}
}

var File_connect_api_proto protoreflect.FileDescriptor

var file_connect_api_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d,
	0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x38, 0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x4b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x4b, 0x65, 0x79, 0x22, 0xda, 0x02,
	0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x71, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70,
	0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x1a, 0x9b, 0x01, 0x0a, 0x05, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x11, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x70, 0x4b, 0x65, 0x79, 0x22, 0x40, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x50, 0x4b, 0x45, 0x59, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x4e, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x02, 0x22, 0x76, 0x0a, 0x09, 0x4b, 0x65,
	0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x1a, 0x2e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x30, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x44, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0x01, 0x2a, 0x51, 0x0a, 0x07, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x44, 0x12, 0x09, 0x0a,
	0x05, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x45, 0x43, 0x45,
	0x49, 0x56, 0x45, 0x5f, 0x48, 0x45, 0x4c, 0x4c, 0x4f, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52,
	0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x48, 0x45, 0x4c, 0x4c, 0x4f, 0x10, 0x02, 0x12, 0x15,
	0x0a, 0x11, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4b, 0x45, 0x45, 0x50, 0x41, 0x4c,
	0x49, 0x56, 0x45, 0x10, 0x03, 0x42, 0x06, 0x5a, 0x04, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connect_api_proto_rawDescOnce sync.Once
	file_connect_api_proto_rawDescData = file_connect_api_proto_rawDesc
)

func file_connect_api_proto_rawDescGZIP() []byte {
	file_connect_api_proto_rawDescOnce.Do(func() {
		file_connect_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_connect_api_proto_rawDescData)
	})
	return file_connect_api_proto_rawDescData
}

var file_connect_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_connect_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_connect_api_proto_goTypes = []interface{}{
	(TYPE_ID)(0),              // 0: TYPE_ID
	(Hello_ERROR)(0),          // 1: Hello.ERROR
	(KeepAlive_ERROR)(0),      // 2: KeepAlive.ERROR
	(*HelloReceive)(nil),      // 3: HelloReceive
	(*Hello)(nil),             // 4: Hello
	(*KeepAlive)(nil),         // 5: KeepAlive
	(*Hello_Request)(nil),     // 6: Hello.Request
	(*Hello_Reply)(nil),       // 7: Hello.Reply
	(*KeepAlive_Request)(nil), // 8: KeepAlive.Request
	(*KeepAlive_Reply)(nil),   // 9: KeepAlive.Reply
	(EncodeType)(0),           // 10: EncodeType
	(Platform)(0),             // 11: Platform
}
var file_connect_api_proto_depIdxs = []int32{
	10, // 0: HelloReceive.server_encodeType:type_name -> EncodeType
	10, // 1: Hello.Request.encodeType:type_name -> EncodeType
	11, // 2: Hello.Request.platform:type_name -> Platform
	10, // 3: Hello.Reply.server_encodeType:type_name -> EncodeType
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_connect_api_proto_init() }
func file_connect_api_proto_init() {
	if File_connect_api_proto != nil {
		return
	}
	file_api_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_connect_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReceive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAlive_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connect_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAlive_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connect_api_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connect_api_proto_goTypes,
		DependencyIndexes: file_connect_api_proto_depIdxs,
		EnumInfos:         file_connect_api_proto_enumTypes,
		MessageInfos:      file_connect_api_proto_msgTypes,
	}.Build()
	File_connect_api_proto = out.File
	file_connect_api_proto_rawDesc = nil
	file_connect_api_proto_goTypes = nil
	file_connect_api_proto_depIdxs = nil
}
