// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: internal.api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TYPE_INTERNAL_ID int32

const (
	TYPE_INTERNAL_ID_INTERNAL_UNUSE_NONE TYPE_INTERNAL_ID = 0
	TYPE_INTERNAL_ID_PUSH_RECEIVE        TYPE_INTERNAL_ID = 1
)

// Enum value maps for TYPE_INTERNAL_ID.
var (
	TYPE_INTERNAL_ID_name = map[int32]string{
		0: "INTERNAL_UNUSE_NONE",
		1: "PUSH_RECEIVE",
	}
	TYPE_INTERNAL_ID_value = map[string]int32{
		"INTERNAL_UNUSE_NONE": 0,
		"PUSH_RECEIVE":        1,
	}
)

func (x TYPE_INTERNAL_ID) Enum() *TYPE_INTERNAL_ID {
	p := new(TYPE_INTERNAL_ID)
	*p = x
	return p
}

func (x TYPE_INTERNAL_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE_INTERNAL_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_proto_enumTypes[0].Descriptor()
}

func (TYPE_INTERNAL_ID) Type() protoreflect.EnumType {
	return &file_internal_api_proto_enumTypes[0]
}

func (x TYPE_INTERNAL_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE_INTERNAL_ID.Descriptor instead.
func (TYPE_INTERNAL_ID) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_proto_rawDescGZIP(), []int{0}
}

type INTERNAL_GROUP int32

const (
	INTERNAL_GROUP_INTERNAL_GROUP_UN_USE INTERNAL_GROUP = 0
	INTERNAL_GROUP_INTERNAL_GROUP_ID     INTERNAL_GROUP = 99
)

// Enum value maps for INTERNAL_GROUP.
var (
	INTERNAL_GROUP_name = map[int32]string{
		0:  "INTERNAL_GROUP_UN_USE",
		99: "INTERNAL_GROUP_ID",
	}
	INTERNAL_GROUP_value = map[string]int32{
		"INTERNAL_GROUP_UN_USE": 0,
		"INTERNAL_GROUP_ID":     99,
	}
)

func (x INTERNAL_GROUP) Enum() *INTERNAL_GROUP {
	p := new(INTERNAL_GROUP)
	*p = x
	return p
}

func (x INTERNAL_GROUP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INTERNAL_GROUP) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_proto_enumTypes[1].Descriptor()
}

func (INTERNAL_GROUP) Type() protoreflect.EnumType {
	return &file_internal_api_proto_enumTypes[1]
}

func (x INTERNAL_GROUP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use INTERNAL_GROUP.Descriptor instead.
func (INTERNAL_GROUP) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_proto_rawDescGZIP(), []int{1}
}

type PushReceive_PUSH_TYPE int32

const (
	PushReceive_TO_ALL        PushReceive_PUSH_TYPE = 0 // receiver not set
	PushReceive_TO_USER       PushReceive_PUSH_TYPE = 1 // receiver là danh sánh user id
	PushReceive_TO_SESSION    PushReceive_PUSH_TYPE = 2 // receiver là danh sách session nhận push
	PushReceive_TO_CONNECTION PushReceive_PUSH_TYPE = 3 // receiver là danh sách connection id
)

// Enum value maps for PushReceive_PUSH_TYPE.
var (
	PushReceive_PUSH_TYPE_name = map[int32]string{
		0: "TO_ALL",
		1: "TO_USER",
		2: "TO_SESSION",
		3: "TO_CONNECTION",
	}
	PushReceive_PUSH_TYPE_value = map[string]int32{
		"TO_ALL":        0,
		"TO_USER":       1,
		"TO_SESSION":    2,
		"TO_CONNECTION": 3,
	}
)

func (x PushReceive_PUSH_TYPE) Enum() *PushReceive_PUSH_TYPE {
	p := new(PushReceive_PUSH_TYPE)
	*p = x
	return p
}

func (x PushReceive_PUSH_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushReceive_PUSH_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_api_proto_enumTypes[2].Descriptor()
}

func (PushReceive_PUSH_TYPE) Type() protoreflect.EnumType {
	return &file_internal_api_proto_enumTypes[2]
}

func (x PushReceive_PUSH_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushReceive_PUSH_TYPE.Descriptor instead.
func (PushReceive_PUSH_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_internal_api_proto_rawDescGZIP(), []int{0, 0}
}

type PushReceive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushReceive) Reset() {
	*x = PushReceive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReceive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReceive) ProtoMessage() {}

func (x *PushReceive) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReceive.ProtoReflect.Descriptor instead.
func (*PushReceive) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_rawDescGZIP(), []int{0}
}

type PushReceive_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PushType       PushReceive_PUSH_TYPE `protobuf:"varint,1,opt,name=pushType,proto3,enum=PushReceive_PUSH_TYPE" json:"pushType,omitempty"`
	Receiver       []string              `protobuf:"bytes,2,rep,name=receiver,proto3" json:"receiver,omitempty"`
	Ignore_Type    PushReceive_PUSH_TYPE `protobuf:"varint,3,opt,name=ignore_Type,json=ignoreType,proto3,enum=PushReceive_PUSH_TYPE" json:"ignore_Type,omitempty"`
	IgnoreReceiver string                `protobuf:"bytes,4,opt,name=ignore_receiver,json=ignoreReceiver,proto3" json:"ignore_receiver,omitempty"`
	ReceiveType    uint32                `protobuf:"varint,5,opt,name=receive_type,json=receiveType,proto3" json:"receive_type,omitempty"`
	RcType         string                `protobuf:"bytes,8,opt,name=rc_type,json=rcType,proto3" json:"rc_type,omitempty"`
	RcGroup        string                `protobuf:"bytes,9,opt,name=rc_group,json=rcGroup,proto3" json:"rc_group,omitempty"`
	Receive        []byte                `protobuf:"bytes,6,opt,name=receive,proto3" json:"receive,omitempty"`
	ReceiveJson    []byte                `protobuf:"bytes,7,opt,name=receive_json,json=receiveJson,proto3" json:"receive_json,omitempty"`
}

func (x *PushReceive_Request) Reset() {
	*x = PushReceive_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReceive_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReceive_Request) ProtoMessage() {}

func (x *PushReceive_Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReceive_Request.ProtoReflect.Descriptor instead.
func (*PushReceive_Request) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PushReceive_Request) GetPushType() PushReceive_PUSH_TYPE {
	if x != nil {
		return x.PushType
	}
	return PushReceive_TO_ALL
}

func (x *PushReceive_Request) GetReceiver() []string {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *PushReceive_Request) GetIgnore_Type() PushReceive_PUSH_TYPE {
	if x != nil {
		return x.Ignore_Type
	}
	return PushReceive_TO_ALL
}

func (x *PushReceive_Request) GetIgnoreReceiver() string {
	if x != nil {
		return x.IgnoreReceiver
	}
	return ""
}

func (x *PushReceive_Request) GetReceiveType() uint32 {
	if x != nil {
		return x.ReceiveType
	}
	return 0
}

func (x *PushReceive_Request) GetRcType() string {
	if x != nil {
		return x.RcType
	}
	return ""
}

func (x *PushReceive_Request) GetRcGroup() string {
	if x != nil {
		return x.RcGroup
	}
	return ""
}

func (x *PushReceive_Request) GetReceive() []byte {
	if x != nil {
		return x.Receive
	}
	return nil
}

func (x *PushReceive_Request) GetReceiveJson() []byte {
	if x != nil {
		return x.ReceiveJson
	}
	return nil
}

type PushReceive_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushReceive_Reply) Reset() {
	*x = PushReceive_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReceive_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReceive_Reply) ProtoMessage() {}

func (x *PushReceive_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReceive_Reply.ProtoReflect.Descriptor instead.
func (*PushReceive_Reply) Descriptor() ([]byte, []int) {
	return file_internal_api_proto_rawDescGZIP(), []int{0, 1}
}

var File_internal_api_proto protoreflect.FileDescriptor

var file_internal_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x03, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x1a, 0xcf, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x08, 0x70, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x2e, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x70, 0x75, 0x73, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x37, 0x0a, 0x0b, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x5f, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x2e, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x69,
	0x67, 0x6e, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x69, 0x67, 0x6e,
	0x6f, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x63, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x63, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x6a,
	0x73, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x47, 0x0a, 0x09, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0a, 0x0a, 0x06,
	0x54, 0x4f, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x4f, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x4f, 0x5f, 0x53, 0x45, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x4f, 0x5f, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x2a, 0x3d, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x13,
	0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x55, 0x4e, 0x55, 0x53, 0x45, 0x5f, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x55, 0x53, 0x48, 0x5f, 0x52, 0x45,
	0x43, 0x45, 0x49, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x42, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4e, 0x54,
	0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x55, 0x4e, 0x5f, 0x55,
	0x53, 0x45, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c,
	0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x49, 0x44, 0x10, 0x63, 0x42, 0x06, 0x5a, 0x04, 0x61,
	0x70, 0x69, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_proto_rawDescOnce sync.Once
	file_internal_api_proto_rawDescData = file_internal_api_proto_rawDesc
)

func file_internal_api_proto_rawDescGZIP() []byte {
	file_internal_api_proto_rawDescOnce.Do(func() {
		file_internal_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_proto_rawDescData)
	})
	return file_internal_api_proto_rawDescData
}

var file_internal_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_internal_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_proto_goTypes = []interface{}{
	(TYPE_INTERNAL_ID)(0),       // 0: TYPE_INTERNAL_ID
	(INTERNAL_GROUP)(0),         // 1: INTERNAL_GROUP
	(PushReceive_PUSH_TYPE)(0),  // 2: PushReceive.PUSH_TYPE
	(*PushReceive)(nil),         // 3: PushReceive
	(*PushReceive_Request)(nil), // 4: PushReceive.Request
	(*PushReceive_Reply)(nil),   // 5: PushReceive.Reply
}
var file_internal_api_proto_depIdxs = []int32{
	2, // 0: PushReceive.Request.pushType:type_name -> PushReceive.PUSH_TYPE
	2, // 1: PushReceive.Request.ignore_Type:type_name -> PushReceive.PUSH_TYPE
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_proto_init() }
func file_internal_api_proto_init() {
	if File_internal_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReceive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReceive_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReceive_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_proto_goTypes,
		DependencyIndexes: file_internal_api_proto_depIdxs,
		EnumInfos:         file_internal_api_proto_enumTypes,
		MessageInfos:      file_internal_api_proto_msgTypes,
	}.Build()
	File_internal_api_proto = out.File
	file_internal_api_proto_rawDesc = nil
	file_internal_api_proto_goTypes = nil
	file_internal_api_proto_depIdxs = nil
}
