// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: market.api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MARKET_TYPE_ID int32

const (
	MARKET_TYPE_ID_MARKET_NONE        MARKET_TYPE_ID = 0
	MARKET_TYPE_ID_REQUEST_PING_API   MARKET_TYPE_ID = 1
	MARKET_TYPE_ID_REQUEST_LIST_API   MARKET_TYPE_ID = 2
	MARKET_TYPE_ID_REQUEST_CREATE_API MARKET_TYPE_ID = 3
	MARKET_TYPE_ID_REQUEST_UPDATE_API MARKET_TYPE_ID = 4
	MARKET_TYPE_ID_REQUEST_DELETE_API MARKET_TYPE_ID = 5
	MARKET_TYPE_ID_REQUEST_LIST_KEY   MARKET_TYPE_ID = 6
	MARKET_TYPE_ID_REQUEST_CREATE_KEY MARKET_TYPE_ID = 7
	MARKET_TYPE_ID_REQUEST_UPDATE_KEY MARKET_TYPE_ID = 8
	MARKET_TYPE_ID_REQUEST_DELETE_KEY MARKET_TYPE_ID = 9
)

// Enum value maps for MARKET_TYPE_ID.
var (
	MARKET_TYPE_ID_name = map[int32]string{
		0: "MARKET_NONE",
		1: "REQUEST_PING_API",
		2: "REQUEST_LIST_API",
		3: "REQUEST_CREATE_API",
		4: "REQUEST_UPDATE_API",
		5: "REQUEST_DELETE_API",
		6: "REQUEST_LIST_KEY",
		7: "REQUEST_CREATE_KEY",
		8: "REQUEST_UPDATE_KEY",
		9: "REQUEST_DELETE_KEY",
	}
	MARKET_TYPE_ID_value = map[string]int32{
		"MARKET_NONE":        0,
		"REQUEST_PING_API":   1,
		"REQUEST_LIST_API":   2,
		"REQUEST_CREATE_API": 3,
		"REQUEST_UPDATE_API": 4,
		"REQUEST_DELETE_API": 5,
		"REQUEST_LIST_KEY":   6,
		"REQUEST_CREATE_KEY": 7,
		"REQUEST_UPDATE_KEY": 8,
		"REQUEST_DELETE_KEY": 9,
	}
)

func (x MARKET_TYPE_ID) Enum() *MARKET_TYPE_ID {
	p := new(MARKET_TYPE_ID)
	*p = x
	return p
}

func (x MARKET_TYPE_ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MARKET_TYPE_ID) Descriptor() protoreflect.EnumDescriptor {
	return file_market_api_proto_enumTypes[0].Descriptor()
}

func (MARKET_TYPE_ID) Type() protoreflect.EnumType {
	return &file_market_api_proto_enumTypes[0]
}

func (x MARKET_TYPE_ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MARKET_TYPE_ID.Descriptor instead.
func (MARKET_TYPE_ID) EnumDescriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{0}
}

type GetListAPI_ERROR int32

const (
	GetListAPI_NO_ERROR GetListAPI_ERROR = 0
)

// Enum value maps for GetListAPI_ERROR.
var (
	GetListAPI_ERROR_name = map[int32]string{
		0: "NO_ERROR",
	}
	GetListAPI_ERROR_value = map[string]int32{
		"NO_ERROR": 0,
	}
)

func (x GetListAPI_ERROR) Enum() *GetListAPI_ERROR {
	p := new(GetListAPI_ERROR)
	*p = x
	return p
}

func (x GetListAPI_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetListAPI_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_market_api_proto_enumTypes[1].Descriptor()
}

func (GetListAPI_ERROR) Type() protoreflect.EnumType {
	return &file_market_api_proto_enumTypes[1]
}

func (x GetListAPI_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetListAPI_ERROR.Descriptor instead.
func (GetListAPI_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{3, 0}
}

type CreateAPI_ERROR int32

const (
	CreateAPI_NO_ERROR                 CreateAPI_ERROR = 0
	CreateAPI_NAME_EMPTY               CreateAPI_ERROR = 1
	CreateAPI_NAME_INVALID             CreateAPI_ERROR = 2
	CreateAPI_SLUG_EMPTY               CreateAPI_ERROR = 3
	CreateAPI_SLUG_INVALID             CreateAPI_ERROR = 4
	CreateAPI_SLUG_EXISTED             CreateAPI_ERROR = 5
	CreateAPI_PROXY_TARGET_URL_INVALID CreateAPI_ERROR = 6
	CreateAPI_PROXY_TARGET_URL_EMPTY   CreateAPI_ERROR = 7
	CreateAPI_ACCESS_DENIED            CreateAPI_ERROR = 8
)

// Enum value maps for CreateAPI_ERROR.
var (
	CreateAPI_ERROR_name = map[int32]string{
		0: "NO_ERROR",
		1: "NAME_EMPTY",
		2: "NAME_INVALID",
		3: "SLUG_EMPTY",
		4: "SLUG_INVALID",
		5: "SLUG_EXISTED",
		6: "PROXY_TARGET_URL_INVALID",
		7: "PROXY_TARGET_URL_EMPTY",
		8: "ACCESS_DENIED",
	}
	CreateAPI_ERROR_value = map[string]int32{
		"NO_ERROR":                 0,
		"NAME_EMPTY":               1,
		"NAME_INVALID":             2,
		"SLUG_EMPTY":               3,
		"SLUG_INVALID":             4,
		"SLUG_EXISTED":             5,
		"PROXY_TARGET_URL_INVALID": 6,
		"PROXY_TARGET_URL_EMPTY":   7,
		"ACCESS_DENIED":            8,
	}
)

func (x CreateAPI_ERROR) Enum() *CreateAPI_ERROR {
	p := new(CreateAPI_ERROR)
	*p = x
	return p
}

func (x CreateAPI_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateAPI_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_market_api_proto_enumTypes[2].Descriptor()
}

func (CreateAPI_ERROR) Type() protoreflect.EnumType {
	return &file_market_api_proto_enumTypes[2]
}

func (x CreateAPI_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateAPI_ERROR.Descriptor instead.
func (CreateAPI_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{4, 0}
}

type DeleteAPI_ERROR int32

const (
	DeleteAPI_NO_ERROR      DeleteAPI_ERROR = 0
	DeleteAPI_API_ID_EMPTY  DeleteAPI_ERROR = 1
	DeleteAPI_API_NOT_FOUND DeleteAPI_ERROR = 2
	DeleteAPI_ACCESS_DENIED DeleteAPI_ERROR = 3
)

// Enum value maps for DeleteAPI_ERROR.
var (
	DeleteAPI_ERROR_name = map[int32]string{
		0: "NO_ERROR",
		1: "API_ID_EMPTY",
		2: "API_NOT_FOUND",
		3: "ACCESS_DENIED",
	}
	DeleteAPI_ERROR_value = map[string]int32{
		"NO_ERROR":      0,
		"API_ID_EMPTY":  1,
		"API_NOT_FOUND": 2,
		"ACCESS_DENIED": 3,
	}
)

func (x DeleteAPI_ERROR) Enum() *DeleteAPI_ERROR {
	p := new(DeleteAPI_ERROR)
	*p = x
	return p
}

func (x DeleteAPI_ERROR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteAPI_ERROR) Descriptor() protoreflect.EnumDescriptor {
	return file_market_api_proto_enumTypes[3].Descriptor()
}

func (DeleteAPI_ERROR) Type() protoreflect.EnumType {
	return &file_market_api_proto_enumTypes[3]
}

func (x DeleteAPI_ERROR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteAPI_ERROR.Descriptor instead.
func (DeleteAPI_ERROR) EnumDescriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{6, 0}
}

type Api struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                // Human readable name of the API. It is used for identification purposes but does not act as an index.
	Slug            string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`                // The URL segment that will map to this API
	ApiId           string `protobuf:"bytes,3,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"` //The identifier for the API This should be unique, but can actually be any kind of string.
	ProxyListenPath string `protobuf:"bytes,4,opt,name=proxy_listen_path,json=proxyListenPath,proto3" json:"proxy_listen_path,omitempty"`
	ProxyTargetUrl  string `protobuf:"bytes,5,opt,name=proxy_target_url,json=proxyTargetUrl,proto3" json:"proxy_target_url,omitempty"`
	Active          bool   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"` //When used in conjunction with the dashboard, if set to false means that on start, restart or reload, the API will be ignored and all paths and routes for that API will cease to be proxied.
	UserCreateId    string `protobuf:"bytes,7,opt,name=user_create_id,json=userCreateId,proto3" json:"user_create_id,omitempty"`
	CreatedAt       uint64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Api) Reset() {
	*x = Api{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api) ProtoMessage() {}

func (x *Api) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api.ProtoReflect.Descriptor instead.
func (*Api) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{0}
}

func (x *Api) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Api) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Api) GetApiId() string {
	if x != nil {
		return x.ApiId
	}
	return ""
}

func (x *Api) GetProxyListenPath() string {
	if x != nil {
		return x.ProxyListenPath
	}
	return ""
}

func (x *Api) GetProxyTargetUrl() string {
	if x != nil {
		return x.ProxyTargetUrl
	}
	return ""
}

func (x *Api) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Api) GetUserCreateId() string {
	if x != nil {
		return x.UserCreateId
	}
	return ""
}

func (x *Api) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Tokenkey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowance        uint32  `protobuf:"varint,1,opt,name=allowance,proto3" json:"allowance,omitempty"` /// allowance & rate: these should be set to the same value, these are the users allowance during a period as set by per.
	Rate             uint32  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Per              uint32  `protobuf:"varint,3,opt,name=per,proto3" json:"per,omitempty"`                                                      // The time in seconds where a rate limit is applied.
	QuotaMax         float64 `protobuf:"fixed64,4,opt,name=quota_max,json=quotaMax,proto3" json:"quota_max,omitempty"`                           // The usage quota for the user. => can only be a positive number, or -1 (unlimited).
	QuotaRenews      float64 `protobuf:"fixed64,5,opt,name=quota_renews,json=quotaRenews,proto3" json:"quota_renews,omitempty"`                  // the Unix timestamp when the quota is renewed.
	QuotaRenewalRate float64 `protobuf:"fixed64,6,opt,name=quota_renewal_rate,json=quotaRenewalRate,proto3" json:"quota_renewal_rate,omitempty"` // The time, in seconds, of when the quota gets renewed (e.g. 86400 would represent 1 day).
	KeyId            string  `protobuf:"bytes,7,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	OrgId            string  `protobuf:"bytes,8,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name             string  `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Expires          float64 `protobuf:"fixed64,10,opt,name=expires,proto3" json:"expires,omitempty"` //The date when the key expires. => expires can only be a positive number, or -1 (unlimited).
	Apis             []*Api  `protobuf:"bytes,11,rep,name=apis,proto3" json:"apis,omitempty"`         // danh sách api mà token này áp dụng
}

func (x *Tokenkey) Reset() {
	*x = Tokenkey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tokenkey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokenkey) ProtoMessage() {}

func (x *Tokenkey) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokenkey.ProtoReflect.Descriptor instead.
func (*Tokenkey) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{1}
}

func (x *Tokenkey) GetAllowance() uint32 {
	if x != nil {
		return x.Allowance
	}
	return 0
}

func (x *Tokenkey) GetRate() uint32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Tokenkey) GetPer() uint32 {
	if x != nil {
		return x.Per
	}
	return 0
}

func (x *Tokenkey) GetQuotaMax() float64 {
	if x != nil {
		return x.QuotaMax
	}
	return 0
}

func (x *Tokenkey) GetQuotaRenews() float64 {
	if x != nil {
		return x.QuotaRenews
	}
	return 0
}

func (x *Tokenkey) GetQuotaRenewalRate() float64 {
	if x != nil {
		return x.QuotaRenewalRate
	}
	return 0
}

func (x *Tokenkey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Tokenkey) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Tokenkey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tokenkey) GetExpires() float64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Tokenkey) GetApis() []*Api {
	if x != nil {
		return x.Apis
	}
	return nil
}

// {"type":400, "group":"MARKET", "request":{"@type":"type.googleapis.com/MarketPing.Request"}}
// ==> {"reply":{"@type":"type.googleapis.com/MarketPing.Reply", "ver":"v0.9.0", "serverTime":"2023-02-06 10:13:17.383644174 +0700 +07 m=+65.934983180"}}
type MarketPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarketPing) Reset() {
	*x = MarketPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPing) ProtoMessage() {}

func (x *MarketPing) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPing.ProtoReflect.Descriptor instead.
func (*MarketPing) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{2}
}

type GetListAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListAPI) Reset() {
	*x = GetListAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListAPI) ProtoMessage() {}

func (x *GetListAPI) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListAPI.ProtoReflect.Descriptor instead.
func (*GetListAPI) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{3}
}

type CreateAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAPI) Reset() {
	*x = CreateAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPI) ProtoMessage() {}

func (x *CreateAPI) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPI.ProtoReflect.Descriptor instead.
func (*CreateAPI) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{4}
}

type UpdateAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAPI) Reset() {
	*x = UpdateAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPI) ProtoMessage() {}

func (x *UpdateAPI) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPI.ProtoReflect.Descriptor instead.
func (*UpdateAPI) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{5}
}

type DeleteAPI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAPI) Reset() {
	*x = DeleteAPI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAPI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPI) ProtoMessage() {}

func (x *DeleteAPI) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPI.ProtoReflect.Descriptor instead.
func (*DeleteAPI) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{6}
}

type GetListKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListKey) Reset() {
	*x = GetListKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListKey) ProtoMessage() {}

func (x *GetListKey) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListKey.ProtoReflect.Descriptor instead.
func (*GetListKey) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{7}
}

type CreateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKey) Reset() {
	*x = CreateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKey) ProtoMessage() {}

func (x *CreateKey) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKey.ProtoReflect.Descriptor instead.
func (*CreateKey) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{8}
}

type UpdateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateKey) Reset() {
	*x = UpdateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKey) ProtoMessage() {}

func (x *UpdateKey) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKey.ProtoReflect.Descriptor instead.
func (*UpdateKey) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{9}
}

type DeleteKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKey) Reset() {
	*x = DeleteKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKey) ProtoMessage() {}

func (x *DeleteKey) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKey.ProtoReflect.Descriptor instead.
func (*DeleteKey) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{10}
}

type MarketPing_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarketPing_Request) Reset() {
	*x = MarketPing_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketPing_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPing_Request) ProtoMessage() {}

func (x *MarketPing_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPing_Request.ProtoReflect.Descriptor instead.
func (*MarketPing_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{2, 0}
}

type MarketPing_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver        string `protobuf:"bytes,1,opt,name=ver,proto3" json:"ver,omitempty"`
	ServerTime string `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
}

func (x *MarketPing_Reply) Reset() {
	*x = MarketPing_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketPing_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketPing_Reply) ProtoMessage() {}

func (x *MarketPing_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketPing_Reply.ProtoReflect.Descriptor instead.
func (*MarketPing_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *MarketPing_Reply) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *MarketPing_Reply) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

type GetListAPI_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchName string `protobuf:"bytes,1,opt,name=search_name,json=searchName,proto3" json:"search_name,omitempty"`
	Page       uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit      uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetListAPI_Request) Reset() {
	*x = GetListAPI_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListAPI_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListAPI_Request) ProtoMessage() {}

func (x *GetListAPI_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListAPI_Request.ProtoReflect.Descriptor instead.
func (*GetListAPI_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetListAPI_Request) GetSearchName() string {
	if x != nil {
		return x.SearchName
	}
	return ""
}

func (x *GetListAPI_Request) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListAPI_Request) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListAPI_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apis      []*Api `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	TotalPage uint32 `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
}

func (x *GetListAPI_Reply) Reset() {
	*x = GetListAPI_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListAPI_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListAPI_Reply) ProtoMessage() {}

func (x *GetListAPI_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListAPI_Reply.ProtoReflect.Descriptor instead.
func (*GetListAPI_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetListAPI_Reply) GetApis() []*Api {
	if x != nil {
		return x.Apis
	}
	return nil
}

func (x *GetListAPI_Reply) GetTotalPage() uint32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

type CreateAPI_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api *Api `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
}

func (x *CreateAPI_Request) Reset() {
	*x = CreateAPI_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAPI_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPI_Request) ProtoMessage() {}

func (x *CreateAPI_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPI_Request.ProtoReflect.Descriptor instead.
func (*CreateAPI_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreateAPI_Request) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type CreateAPI_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api *Api `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
}

func (x *CreateAPI_Reply) Reset() {
	*x = CreateAPI_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAPI_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPI_Reply) ProtoMessage() {}

func (x *CreateAPI_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPI_Reply.ProtoReflect.Descriptor instead.
func (*CreateAPI_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{4, 1}
}

func (x *CreateAPI_Reply) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type UpdateAPI_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api *Api `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
}

func (x *UpdateAPI_Request) Reset() {
	*x = UpdateAPI_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAPI_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPI_Request) ProtoMessage() {}

func (x *UpdateAPI_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPI_Request.ProtoReflect.Descriptor instead.
func (*UpdateAPI_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateAPI_Request) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type UpdateAPI_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api *Api `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
}

func (x *UpdateAPI_Reply) Reset() {
	*x = UpdateAPI_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAPI_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPI_Reply) ProtoMessage() {}

func (x *UpdateAPI_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPI_Reply.ProtoReflect.Descriptor instead.
func (*UpdateAPI_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{5, 1}
}

func (x *UpdateAPI_Reply) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

type DeleteAPI_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiId string `protobuf:"bytes,1,opt,name=api_id,json=apiId,proto3" json:"api_id,omitempty"`
}

func (x *DeleteAPI_Request) Reset() {
	*x = DeleteAPI_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAPI_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPI_Request) ProtoMessage() {}

func (x *DeleteAPI_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPI_Request.ProtoReflect.Descriptor instead.
func (*DeleteAPI_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DeleteAPI_Request) GetApiId() string {
	if x != nil {
		return x.ApiId
	}
	return ""
}

type DeleteAPI_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAPI_Reply) Reset() {
	*x = DeleteAPI_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAPI_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPI_Reply) ProtoMessage() {}

func (x *DeleteAPI_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPI_Reply.ProtoReflect.Descriptor instead.
func (*DeleteAPI_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{6, 1}
}

type GetListKey_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search  string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Page    uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage uint32 `protobuf:"varint,3,opt,name=perPage,proto3" json:"perPage,omitempty"`
}

func (x *GetListKey_Request) Reset() {
	*x = GetListKey_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListKey_Request) ProtoMessage() {}

func (x *GetListKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListKey_Request.ProtoReflect.Descriptor instead.
func (*GetListKey_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetListKey_Request) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetListKey_Request) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListKey_Request) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type GetListKey_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys      []*Tokenkey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	TotalPage uint32      `protobuf:"varint,2,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
}

func (x *GetListKey_Reply) Reset() {
	*x = GetListKey_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListKey_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListKey_Reply) ProtoMessage() {}

func (x *GetListKey_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListKey_Reply.ProtoReflect.Descriptor instead.
func (*GetListKey_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetListKey_Reply) GetKeys() []*Tokenkey {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *GetListKey_Reply) GetTotalPage() uint32 {
	if x != nil {
		return x.TotalPage
	}
	return 0
}

type CreateKey_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateKey_Request) Reset() {
	*x = CreateKey_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKey_Request) ProtoMessage() {}

func (x *CreateKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKey_Request.ProtoReflect.Descriptor instead.
func (*CreateKey_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{8, 0}
}

type CreateKey_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys *Tokenkey `protobuf:"bytes,1,opt,name=keys,proto3" json:"keys,omitempty"`
}

func (x *CreateKey_Reply) Reset() {
	*x = CreateKey_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKey_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKey_Reply) ProtoMessage() {}

func (x *CreateKey_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKey_Reply.ProtoReflect.Descriptor instead.
func (*CreateKey_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{8, 1}
}

func (x *CreateKey_Reply) GetKeys() *Tokenkey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type UpdateKey_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys *Tokenkey `protobuf:"bytes,1,opt,name=keys,proto3" json:"keys,omitempty"`
}

func (x *UpdateKey_Request) Reset() {
	*x = UpdateKey_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKey_Request) ProtoMessage() {}

func (x *UpdateKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKey_Request.ProtoReflect.Descriptor instead.
func (*UpdateKey_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateKey_Request) GetKeys() *Tokenkey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type UpdateKey_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys *Tokenkey `protobuf:"bytes,1,opt,name=keys,proto3" json:"keys,omitempty"`
}

func (x *UpdateKey_Reply) Reset() {
	*x = UpdateKey_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateKey_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKey_Reply) ProtoMessage() {}

func (x *UpdateKey_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKey_Reply.ProtoReflect.Descriptor instead.
func (*UpdateKey_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{9, 1}
}

func (x *UpdateKey_Reply) GetKeys() *Tokenkey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteKey_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
}

func (x *DeleteKey_Request) Reset() {
	*x = DeleteKey_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKey_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKey_Request) ProtoMessage() {}

func (x *DeleteKey_Request) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKey_Request.ProtoReflect.Descriptor instead.
func (*DeleteKey_Request) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DeleteKey_Request) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteKey_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKey_Reply) Reset() {
	*x = DeleteKey_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_api_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKey_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKey_Reply) ProtoMessage() {}

func (x *DeleteKey_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_market_api_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKey_Reply.ProtoReflect.Descriptor instead.
func (*DeleteKey_Reply) Descriptor() ([]byte, []int) {
	return file_market_api_proto_rawDescGZIP(), []int{10, 1}
}

var File_market_api_proto protoreflect.FileDescriptor

var file_market_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xf7, 0x01, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c,
	0x75, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x69, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x50, 0x61, 0x74, 0x68, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x72, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x75, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xb2, 0x02, 0x0a,
	0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x4d, 0x61, 0x78, 0x12, 0x21, 0x0a, 0x0c, 0x71, 0x75,
	0x6f, 0x74, 0x61, 0x5f, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x73, 0x12, 0x2c, 0x0a,
	0x12, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x52, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6b,
	0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x72, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x04, 0x61, 0x70, 0x69, 0x73, 0x18,
	0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x61, 0x70, 0x69, 0x52, 0x04, 0x61, 0x70, 0x69,
	0x73, 0x22, 0x53, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x1a,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3a, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x50, 0x49, 0x1a, 0x54, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x40, 0x0a, 0x05, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x04, 0x61, 0x70, 0x69, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x04, 0x2e, 0x61, 0x70, 0x69, 0x52, 0x04, 0x61, 0x70, 0x69, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x22, 0x15, 0x0a,
	0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x00, 0x22, 0x8a, 0x02, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x50, 0x49, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x61, 0x70, 0x69,
	0x52, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x61, 0x70,
	0x69, 0x52, 0x03, 0x61, 0x70, 0x69, 0x22, 0xb8, 0x01, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4c, 0x55, 0x47, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x03,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x4c, 0x55, 0x47, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x4c, 0x55, 0x47, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54,
	0x45, 0x44, 0x10, 0x05, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x54, 0x41,
	0x52, 0x47, 0x45, 0x54, 0x5f, 0x55, 0x52, 0x4c, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44,
	0x10, 0x06, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x52, 0x4f, 0x58, 0x59, 0x5f, 0x54, 0x41, 0x52, 0x47,
	0x45, 0x54, 0x5f, 0x55, 0x52, 0x4c, 0x5f, 0x45, 0x4d, 0x50, 0x54, 0x59, 0x10, 0x07, 0x12, 0x11,
	0x0a, 0x0d, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10,
	0x08, 0x22, 0x4f, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x50, 0x49, 0x1a, 0x21,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x03, 0x61, 0x70, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x61, 0x70, 0x69, 0x52, 0x03, 0x61, 0x70,
	0x69, 0x1a, 0x1f, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x03, 0x61, 0x70,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x61, 0x70, 0x69, 0x52, 0x03, 0x61,
	0x70, 0x69, 0x22, 0x85, 0x01, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x50, 0x49,
	0x1a, 0x20, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x61,
	0x70, 0x69, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x69,
	0x49, 0x64, 0x1a, 0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4d, 0x0a, 0x05, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x50, 0x49, 0x5f, 0x49, 0x44, 0x5f, 0x45, 0x4d, 0x50,
	0x54, 0x59, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x50, 0x49, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x03, 0x22, 0xa4, 0x01, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x1a, 0x4f, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x1a, 0x45, 0x0a, 0x05, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67,
	0x65, 0x22, 0x3e, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0x09,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x0a, 0x05, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x22, 0x5d, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0x28,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6b,
	0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x1a, 0x26, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x1d, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x6b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73,
	0x22, 0x36, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x1a, 0x20, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x1a,
	0x07, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0xf3, 0x01, 0x0a, 0x0e, 0x4d, 0x41, 0x52,
	0x4b, 0x45, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x44, 0x12, 0x0f, 0x0a, 0x0b, 0x4d,
	0x41, 0x52, 0x4b, 0x45, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x5f, 0x41, 0x50, 0x49,
	0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4c, 0x49,
	0x53, 0x54, 0x5f, 0x41, 0x50, 0x49, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x10, 0x03,
	0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x41, 0x50, 0x49, 0x10, 0x05,
	0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x4c, 0x49, 0x53, 0x54,
	0x5f, 0x4b, 0x45, 0x59, 0x10, 0x06, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x4b, 0x45, 0x59, 0x10, 0x07, 0x12, 0x16,
	0x0a, 0x12, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45,
	0x5f, 0x4b, 0x45, 0x59, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x4b, 0x45, 0x59, 0x10, 0x09, 0x42, 0x06,
	0x5a, 0x04, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_api_proto_rawDescOnce sync.Once
	file_market_api_proto_rawDescData = file_market_api_proto_rawDesc
)

func file_market_api_proto_rawDescGZIP() []byte {
	file_market_api_proto_rawDescOnce.Do(func() {
		file_market_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_api_proto_rawDescData)
	})
	return file_market_api_proto_rawDescData
}

var file_market_api_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_market_api_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_market_api_proto_goTypes = []interface{}{
	(MARKET_TYPE_ID)(0),        // 0: MARKET_TYPE_ID
	(GetListAPI_ERROR)(0),      // 1: GetListAPI.ERROR
	(CreateAPI_ERROR)(0),       // 2: CreateAPI.ERROR
	(DeleteAPI_ERROR)(0),       // 3: DeleteAPI.ERROR
	(*Api)(nil),                // 4: api
	(*Tokenkey)(nil),           // 5: tokenkey
	(*MarketPing)(nil),         // 6: MarketPing
	(*GetListAPI)(nil),         // 7: GetListAPI
	(*CreateAPI)(nil),          // 8: CreateAPI
	(*UpdateAPI)(nil),          // 9: UpdateAPI
	(*DeleteAPI)(nil),          // 10: DeleteAPI
	(*GetListKey)(nil),         // 11: GetListKey
	(*CreateKey)(nil),          // 12: CreateKey
	(*UpdateKey)(nil),          // 13: UpdateKey
	(*DeleteKey)(nil),          // 14: DeleteKey
	(*MarketPing_Request)(nil), // 15: MarketPing.Request
	(*MarketPing_Reply)(nil),   // 16: MarketPing.Reply
	(*GetListAPI_Request)(nil), // 17: GetListAPI.Request
	(*GetListAPI_Reply)(nil),   // 18: GetListAPI.Reply
	(*CreateAPI_Request)(nil),  // 19: CreateAPI.Request
	(*CreateAPI_Reply)(nil),    // 20: CreateAPI.Reply
	(*UpdateAPI_Request)(nil),  // 21: UpdateAPI.Request
	(*UpdateAPI_Reply)(nil),    // 22: UpdateAPI.Reply
	(*DeleteAPI_Request)(nil),  // 23: DeleteAPI.Request
	(*DeleteAPI_Reply)(nil),    // 24: DeleteAPI.Reply
	(*GetListKey_Request)(nil), // 25: GetListKey.Request
	(*GetListKey_Reply)(nil),   // 26: GetListKey.Reply
	(*CreateKey_Request)(nil),  // 27: CreateKey.Request
	(*CreateKey_Reply)(nil),    // 28: CreateKey.Reply
	(*UpdateKey_Request)(nil),  // 29: UpdateKey.Request
	(*UpdateKey_Reply)(nil),    // 30: UpdateKey.Reply
	(*DeleteKey_Request)(nil),  // 31: DeleteKey.Request
	(*DeleteKey_Reply)(nil),    // 32: DeleteKey.Reply
}
var file_market_api_proto_depIdxs = []int32{
	4,  // 0: tokenkey.apis:type_name -> api
	4,  // 1: GetListAPI.Reply.apis:type_name -> api
	4,  // 2: CreateAPI.Request.api:type_name -> api
	4,  // 3: CreateAPI.Reply.api:type_name -> api
	4,  // 4: UpdateAPI.Request.api:type_name -> api
	4,  // 5: UpdateAPI.Reply.api:type_name -> api
	5,  // 6: GetListKey.Reply.keys:type_name -> tokenkey
	5,  // 7: CreateKey.Reply.keys:type_name -> tokenkey
	5,  // 8: UpdateKey.Request.keys:type_name -> tokenkey
	5,  // 9: UpdateKey.Reply.keys:type_name -> tokenkey
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_market_api_proto_init() }
func file_market_api_proto_init() {
	if File_market_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Api); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tokenkey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAPI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketPing_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketPing_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListAPI_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListAPI_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAPI_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAPI_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAPI_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAPI_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAPI_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAPI_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListKey_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListKey_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKey_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKey_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKey_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateKey_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKey_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_api_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKey_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_api_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_api_proto_goTypes,
		DependencyIndexes: file_market_api_proto_depIdxs,
		EnumInfos:         file_market_api_proto_enumTypes,
		MessageInfos:      file_market_api_proto_msgTypes,
	}.Build()
	File_market_api_proto = out.File
	file_market_api_proto_rawDesc = nil
	file_market_api_proto_goTypes = nil
	file_market_api_proto_depIdxs = nil
}
